### ISSUE TITLE
Request: Ex Raid Start time

### ISSUE THREAD

**Issue by PJMan7** [peter-obrien/organizer#17]
Could we please get the start time added to the Ex-Raid Cards. I have found that users will sometimes think the posted time is start and not end.

**Comment by peter-obrien** [comment]
Historically, it seems like EX raids have a duration of 45 minutes.  For now I will just use that as an assumption going forward and just derive the start time from the provided end time.

**Comment by peter-obrien** [comment]
![image](https://user-images.githubusercontent.com/6796868/42412250-82fb71c8-81d6-11e8-8770-dc1c1a3652f2.png)
