### ISSUE TITLE
2000 character Cap issue 

### ISSUE THREAD

**Issue by PJMan7** [peter-obrien/organizer#19]
![image](https://user-images.githubusercontent.com/26701093/43911143-b762dd92-9bcc-11e8-865b-761b657422e4.png)

when trying to run the command !zones the discord buffer ran out of space to handle the output in one message.

i have provided the error within the python script that was running.

**Comment by peter-obrien** [comment]
Fixed by 6a642d12c59608f19b9da07146e366fc9da76dee
